server:
  port: ${PORT:8086}
  
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
       discovery:
        locator:
          enabled: true
       routes:
        - id: account-service-get
          uri: lb://rollingstone-ecommerce-new-account-api
          predicates:
          - Method=GET
          - Path=/api/account/**
          filters:
          - RewritePath=/api/account/(?<path>.*), /$\{path}
        - id: account-service-post
          uri: lb://rollingstone-ecommerce-new-account-api
          predicates:
          - Method=POST
          - Path=/api/account/**
          filters:
          - RewritePath=/api/account/(?<path>.*), /$\{path}
        - id: account-service-put
          uri: lb://rollingstone-ecommerce-new-account-api
          predicates:
          - Method=PUT
          - Path=/api/account/**
          filters:
          - RewritePath=/api/account/(?<path>.*), /$\{path}
        - id: account-service-delete
          uri: lb://rollingstone-ecommerce-new-account-api
          predicates:
          - Method=DELETE
          - Path=/api/account/**
          filters:
          - RewritePath=/api/account/(?<path>.*), /$\{path}